service: lambda-server
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  environment:
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  createCheckoutSession:
    handler: handler.createCheckoutSession
    events:
      - httpApi:
          path: /create-checkout-session
          method: POST
          cors: true
      

plugins:
  - serverless-offline
  - serverless-iam-roles-per-function
